### ISSUE TITLE
Error state improvement

### ISSUE THREAD

**Issue by mrcodegit** [OlegSirbu/reposearch#2]
Repro steps:

1. use invalid token in .env
2. start app

current result:
1. initially we see "Oops, an error occurred. Please try again or check your GitHub token in README." (correct)
2. after typing in search input we see 
![Screenshot 2023-11-28 at 15 31 41](https://github.com/OlegSirbu/reposearch/assets/49042542/cc892464-6e02-49ed-a055-bcbf38d0e001)

expected result:
1. initially we see "Oops, an error occurred. Please try again or check your GitHub token in README." (correct)
2. handle search input, dont show runtime error

**Comment by olehsyrbu** [comment]
@mrcodegit

"I've fixed the problem in the last commit. The issue was in the handleSearch callback. I simply removed this:
```
fetchMore({
  variables: {
    query: newQuery,
    first: PAGE_SIZE,
    after: null,
  },
});
```
A better approach would be to wrap it with an ErrorBoundary component. However, since this is not a production version, I decided to leave my last approach as is."

**Comment by mrcodegit** [comment]
@OlegSirbu thanks for solving this. Another solution would be to add .catch()

`   fetchMore({
      variables: {
        query: newQuery,
        first: PAGE_SIZE,
        after: null,
      },
    }).catch(e => {});`
